remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Categorization Model of Predicting LOL Game Outcomes]
description: [A short description of your site's purpose]

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
